# Generated by Django 5.1 on 2024-08-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('idade', models.IntegerField(max_length=2, verbose_name='Idade')),
                ('cpf', models.IntegerField(max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.IntegerField(max_length=11, verbose_name='Telefone')),
                ('competencias', models.CharField(max_length=3000, verbose_name='Competencias')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('idade', models.IntegerField(max_length=120, verbose_name='Idade')),
                ('cpf', models.IntegerField(max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.IntegerField(max_length=11, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('nednereco', models.IntegerField(max_length=10, verbose_name='Numero')),
                ('necessidade', models.CharField(max_length=3000, verbose_name='Necessidade')),
            ],
        ),
    ]
