# Generated by Django 5.1.3 on 2024-12-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cuidador_paciente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='competencias',
            field=models.TextField(max_length=3000, verbose_name='Competencias'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='idade',
            field=models.PositiveIntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='telefone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.PositiveIntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='necessidade',
            field=models.TextField(max_length=3000, verbose_name='Necessidade'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
    ]
